### ISSUE TITLE
Error when trying to add user image

### ISSUE THREAD

**Issue by jmartsch** [ryancramerdesign/LoginFacebook#1]
When I try to map the Facebook picture to a field I added to the user template (user_image) I get an error: 
![image](https://user-images.githubusercontent.com/551551/29002101-26727318-7a9b-11e7-8bdb-4ae83151e83b.png)

The error shows: Exception: Item added to ProcessWire\Pageimages is not an allowed type.

Here is how my field is configured:
![image](https://user-images.githubusercontent.com/551551/29002109-46efa912-7a9b-11e7-9a6b-9c64a454367e.png)

I also tried it with Formatted value = Automatic and a field which was a text field, but that doesn´t work either.

**Comment by ryancramerdesign** [comment]
Unfortunately Facebook doesn't allow the server to see the image, only the
client-side logged in user. So ProcessWire can't see the image, but the
user can. Meaning, you can display an <img> tag with the value (which
points to a facebook URL) but you can't pull it into an image field in
ProcessWire.
